// Seed data for BYSS GROUP CRM
// Run with: npx tsx src/lib/db/seed.ts

export const SEED_PROSPECTS = [
  {
    name: "Digicel (via WITH-YOU)",
    sector: "Télécom",
    phase: "negotiation",
    score: 5,
    probability: 70,
    estimatedBasket: "54000",
    keyContact: "Victor Despointes",
    email: "victor@withyou.fr",
    phone: "",
    nextAction: "RDV formel 23 mars — 3 options SPIN",
    optionChosen: "Croissance",
    mrr: "4500",
    memorablePhrase: "Dingue !!",
    aiScore: "hot",
    notes: "Victor a dit 'Dingue!!' en voyant la démo. 72 vidéos/an à 750€ HT. Passage ouvert.",
  },
  {
    name: "Wizzee",
    sector: "Télécom",
    phase: "signed",
    score: 4,
    probability: 100,
    estimatedBasket: "18000",
    keyContact: "",
    nextAction: "Maintenance Google Ads + Meta",
    optionChosen: "Growth",
    mrr: "1500",
    memorablePhrase: "Fatigue créative — CPA qui grimpe.",
    aiScore: "hot",
  },
  {
    name: "GoodCircle",
    sector: "ESG/RSE",
    phase: "signed",
    score: 4,
    probability: 100,
    estimatedBasket: "12000",
    keyContact: "",
    nextAction: "Maintenance Google Ads + Meta",
    optionChosen: "Growth",
    mrr: "1000",
    memorablePhrase: "B2B ESG — positionnement unique.",
    aiScore: "hot",
  },
  {
    name: "MIZA",
    sector: "Restaurant",
    phase: "prospect",
    score: 3,
    probability: 40,
    estimatedBasket: "5000",
    keyContact: "Chef",
    nextAction: "Réserver table. Manger. Observer. Sentir. Parler au chef.",
    memorablePhrase: "Ta cuisine mérite un film. Pas une brochure.",
    aiScore: "warm",
    notes: "Zero case. Pipeline image prêt (10 images pack). Arriver avec tablette.",
  },
  {
    name: "Alpha Diving",
    sector: "Excursion",
    phase: "contacted",
    score: 3,
    probability: 30,
    estimatedBasket: "12000",
    keyContact: "",
    nextAction: "J+7 follow-up — a reçu la démo vendredi",
    memorablePhrase: "Le touriste à 22h ne sait pas que tes fonds marins existent.",
    aiScore: "warm",
  },
  {
    name: "Karibea Hotels",
    sector: "Hôtellerie",
    phase: "negotiation",
    score: 4,
    probability: 50,
    estimatedBasket: "45000",
    keyContact: "",
    nextAction: "Proposition 3 options + ROI anti-OTA",
    memorablePhrase: "Booking prend 15%. BYSS GROUP les rend.",
    aiScore: "warm",
  },
  {
    name: "Habitation Clément",
    sector: "Rhum/Distillerie",
    phase: "prospect",
    score: 4,
    probability: 25,
    estimatedBasket: "35000",
    keyContact: "Naomie Phanor",
    nextAction: "Visiter. Pas pour vendre. Pour comprendre.",
    memorablePhrase: "63 morts. 1 survivant. 1 château face au volcan. Personne n'a encore filmé cette histoire.",
    aiScore: "cold",
  },
  {
    name: "Fort-de-France (via BIXA)",
    sector: "Institution",
    phase: "demo_done",
    score: 5,
    probability: 80,
    estimatedBasket: "25000",
    keyContact: "",
    nextAction: "Finaliser commande An tan lontan + Césaire Pixar",
    memorablePhrase: "Raconter l'histoire. Autrement.",
    aiScore: "hot",
    notes: "Commande reçue. Montants à chiffrer.",
  },
  {
    name: "Kata Mambo",
    sector: "Excursion",
    phase: "contacted",
    score: 3,
    probability: 35,
    estimatedBasket: "8000",
    keyContact: "",
    nextAction: "J+7 relance",
    memorablePhrase: "Le silence entre deux souffles de dauphin.",
    aiScore: "warm",
  },
  {
    name: "CCI Martinique",
    sector: "Institution",
    phase: "prospect",
    score: 5,
    probability: 60,
    estimatedBasket: "15000",
    keyContact: "Pascal Fardin",
    nextAction: "Email RDV — programme digitalisation",
    memorablePhrase: "5000 entreprises. 1 porte.",
    aiScore: "warm",
    notes: "Canal passif. Foyer éternel. Ne s'éteint jamais.",
  },
];

export const SEED_PROJECTS = [
  { name: "Orion", slug: "orion", description: "SaaS CMO Unifié — 90 agents, 24 plateformes", status: "active", externalUrl: "https://orion.byssgroup.fr", icon: "Orbit", color: "#00B4D8", orderIndex: 1, isPublic: true, isVisible: true },
  { name: "Byss Emploi", slug: "byss-emploi", description: "Emploi IA — Seul MCP France Travail", status: "active", externalUrl: "https://byssemploi.fr", icon: "Briefcase", color: "#4ADE80", orderIndex: 2, isPublic: true, isVisible: true },
  { name: "Random", slug: "random", description: "App sociale — 5 inconnus, 1 bar, 1€", status: "active", externalUrl: "https://random.byssgroup.fr", icon: "Shuffle", color: "#F97316", orderIndex: 3, isPublic: true, isVisible: true },
  { name: "MOOSTIK", slug: "moostik", description: "Animation virale — 349K vues", status: "active", externalUrl: "https://moostik.byssgroup.fr", icon: "Tv", color: "#E94560", orderIndex: 4, isPublic: true, isVisible: true },
  { name: "Jurassic Wars", slug: "jurassic-wars", description: "Univers gaming complet — Villages, Confédération, Traducteur", status: "active", externalUrl: "https://jurassicwars.byssgroup.fr", icon: "Swords", color: "#8B5CF6", orderIndex: 5, isPublic: true, isVisible: true },
  { name: "Cadifor", slug: "cadifor", description: "Doctrine 997 pages — Système d'exploitation cognitif", status: "active", icon: "Crown", color: "#00B4D8", orderIndex: 6, isPublic: true, isVisible: true },
  { name: "Toxic", slug: "toxic", description: "Rap créole — Le feu sacré", status: "active", icon: "Flame", color: "#E94560", orderIndex: 7, isPublic: true, isVisible: true },
  { name: "Byss News", slug: "byss-news", description: "Veille géopolitique — 1392 signaux", status: "active", icon: "Newspaper", color: "#3B82F6", orderIndex: 8, isPublic: true, isVisible: true },
  { name: "SOTAI", slug: "sotai", description: "Production vidéo IA collective", status: "active", icon: "Video", color: "#F5D76E", orderIndex: 9, isPublic: true, isVisible: true },
  { name: "APEX 972", slug: "apex-972", description: "Pipeline leads Zenith Eco — 120 leads/mois", status: "active", icon: "Target", color: "#4ADE80", orderIndex: 10, isPublic: false, isVisible: true },
  { name: "FM12", slug: "fm12", description: "La durée comme arme", status: "active", icon: "Clock", color: "#8888A0", orderIndex: 11, isPublic: true, isVisible: false },
  { name: "An tan lontan", slug: "an-tan-lontan", description: "Docusérie histoire de la Martinique", status: "dev", icon: "History", color: "#00B4D8", orderIndex: 12, isPublic: false, isVisible: true },
  { name: "Césaire Pixar", slug: "cesaire-pixar", description: "Animation vie d'Aimé Césaire", status: "dev", icon: "Sparkles", color: "#A855F7", orderIndex: 13, isPublic: false, isVisible: true },
  { name: "Éveil", slug: "eveil", description: "Mouvement politique — CTM 2028", status: "active", icon: "Sun", color: "#F97316", orderIndex: 14, isPublic: false, isVisible: true },
  { name: "Lignée", slug: "lignee", description: "Capital généalogique Bissol — 1889-2026", status: "active", icon: "GitBranch", color: "#00B4D8", orderIndex: 15, isPublic: false, isVisible: true },
];

export const SEED_ACTIVITIES = [
  { type: "email", title: "Email envoyé à Alpha Diving", description: "Follow-up J+3 après démo" },
  { type: "invoice", title: "Facture BG-2026-001 créée", description: "Wizzee — Mars 2026 — 1500€ HT" },
  { type: "prospect", title: "Prospect MIZA ajouté", description: "Restaurant — Zero case pipeline image" },
  { type: "meeting", title: "RDV Victor Despointes confirmé", description: "23 mars 14h — Digicel 3 options" },
  { type: "video", title: "Vidéo MOOSTIK livrée", description: "Épisode 4 — Evil Pichon voix" },
  { type: "ai", title: "Briefing généré par Sorel", description: "3 follow-ups, 1 RDV, pipeline 42K€ signé" },
];
